package com.crafter.structure.minecraft

object Helper {
    val AVAILABLE_MINECRAFT_COMMANDS: List<String> = listOf(
        "ban",
        "ban-ip",
        "banlist",
        "deop",
        "kick",
        "list",
        "op",
        "pardon",
        "pardon",
        "save-all",
        "save-off",
        "save-on",
        "stop",
        "whitelist add",
        "whitelist remove",
        "whitelist list",
        "whitelist on",
        "whitelist off",
        "whitelist reload",
        "help",
        "give",
        "tp",
        "kill",
        "weather",
        "gamemode creative",
        "gamemode survival",
        "gamemode spectator",
        "time",
        "difficulty",
        "seed",
        "summon",
        "atlantis",
        "instantmine",
        "falldamage",
        "waterdamage",
        "firedamage",
        "duplicate",
        "dropstore",
        "instantplant",
        "gamerule keepInventory true",
        "gamerule",
        "ride",
        "Freeze",
        "superheat",
        "itemdamage",
        "locate",
        "camerashake",
        "clearspawnpoint",
        "connect",
        "deop",
        "dialogue",
        "effect",
        "enchant",
        "event",
        "fill",
        "fog",
        "damage",
        "execute summon"
    )
}